version: '2'
services:
  hdfs-name:
    image: quay.io/geodocker/hdfs:0.1
    command: name
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
    ports:
      - 50070:50070
  hdfs-data:
    image: quay.io/geodocker/hdfs:0.1
    command: data
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
    depends_on:
      - hdfs-name
  zookeeper:
    image: quay.io/geodocker/zookeeper:latest
    ports:
      - 2181:2181
  accumulo-master:
    image: quay.io/geodocker/accumulo:latest
    command: master --auto-init
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
      ZOOKEEPERS: zookeeper
      ACCUMULO_PASSWORD: GisPwd
  accumulo-monitor:
    image: quay.io/geodocker/accumulo:latest
    command: monitor
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
      ZOOKEEPERS: zookeeper
    ports:
      - 50095:50095
    depends_on:
      - zookeeper
      - accumulo-master
  accumulo-tserver:
    image: quay.io/geodocker/accumulo:latest
    command: tserver
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
      ZOOKEEPERS: zookeeper
    depends_on:
      - zookeeper
      - accumulo-master
  accumulo-proxy:
    image: quay.io/geodocker/accumulo:latest
    command: bash -c "sleep 45s && echo 'useMockInstance=false' > /opt/accumulo/proxy/proxy.properties && echo 'useMiniAccumulo=false' >> /opt/accumulo/proxy/proxy.properties && echo 'tokenClass=org.apache.accumulo.core.client.security.tokens.PasswordToken' >> /opt/accumulo/proxy/proxy.properties && echo 'port=33333' >> /opt/accumulo/proxy/proxy.properties && echo 'maxFrameSize=16M' >> /opt/accumulo/proxy/proxy.properties && echo 'instance=accumulo' >> /opt/accumulo/proxy/proxy.properties && echo 'zookeepers=zookeeper:2181' >> /opt/accumulo/proxy/proxy.properties && /opt/accumulo/bin/accumulo proxy -p /opt/accumulo/proxy/proxy.properties"
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
      ZOOKEEPERS: zookeeper
    ports:
      - 33333:33333
    depends_on:
      - zookeeper
      - accumulo-master
      - hdfs-name
      - hdfs-data
